// Sound-effect tracker.
//   npm run sfx
// Looks at public/sounds, compares it with data/sfx-catalog.json and writes:
//   public/sounds/manifest.json   what the game may load (no entry = no request = no 404)
//   docs/SFX-TRACKER.md           what you have and what you still need (markdown)
//   tools/sfx-data.js             the same data for tools/sfx-tracker.html (open it in a browser to see and play your sounds)
//
// A sound is `name.mp3` or up to three variants `name_1.mp3`, `name_2.mp3`, `name_3.mp3`
// (a - works as well as _, and .ogg, .wav and .webm also work).

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const DIR = join(root, 'public', 'sounds');
const MAX_VARIANTS = 3;
const EXT = /\.(mp3|ogg|wav|webm)$/i;

interface Entry { name: string; group: string; length: string; priority: boolean; wired: boolean; plays: string; search: string }
const catalog = (JSON.parse(readFileSync(join(root, 'data', 'sfx-catalog.json'), 'utf8')) as { sounds: Entry[] }).sounds;
const names = new Set(catalog.map((c) => c.name));

const files = readdirSync(DIR).filter((f) => EXT.test(f)).sort();
const found = new Map<string, { file: string; n: number }[]>();
const unknown: string[] = [];
const extra: string[] = [];
for (const f of files) {
  // Names may use - or _ (card-flip_1.mp3, card_flip_2.mp3); a trailing -1 / _1 is the variant number.
  const stem = f.replace(EXT, '').replace(/_/g, '-').toLowerCase();
  let name = stem;
  let n = 0;
  if (!names.has(stem)) {
    const m = /^(.+)-([1-9])$/.exec(stem);
    if (m && names.has(m[1]!)) { name = m[1]!; n = Number(m[2]); } else { unknown.push(f); continue; }
  }
  if (n > MAX_VARIANTS) { extra.push(f); continue; }
  const list = found.get(name) ?? [];
  list.push({ file: f, n });
  found.set(name, list);
}

const manifest: Record<string, string[]> = {};
for (const c of catalog) {
  const list = found.get(c.name);
  if (list) manifest[c.name] = list.sort((a, b) => a.n - b.n).slice(0, MAX_VARIANTS).map((x) => x.file);
}
writeFileSync(join(DIR, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
// A plain script (not JSON) so tools/sfx-tracker.html also works when opened straight from disk.
writeFileSync(join(root, 'tools', 'sfx-data.js'), `window.SFX = ${JSON.stringify({ maxVariants: MAX_VARIANTS, catalog, manifest, unknown, extra })};\n`);

// --- the tracker ---------------------------------------------------------------
const have = catalog.filter((c) => manifest[c.name]);
const priority = catalog.filter((c) => c.priority);
const mark = (c: Entry): string => {
  const v = manifest[c.name]?.length ?? 0;
  return v === 0 ? '❌ missing' : v >= MAX_VARIANTS ? `✅ ${v}/${MAX_VARIANTS}` : `🟡 ${v}/${MAX_VARIANTS} variants`;
};
let md = '# Sound effects tracker\n\n';
md += '_Generated by `npm run sfx` from `public/sounds` and `data/sfx-catalog.json`. Do not edit by hand._\n\n';
md += `**${have.length} of ${catalog.length}** sounds present. Priority sounds (★): **${priority.filter((c) => manifest[c.name]).length} of ${priority.length}**. `;
md += `Wired into the game: **${catalog.filter((c) => c.wired).length}** (the rest are listed so you can find them now; they play once the game uses them).\n\n`;
md += 'Name files `name.mp3`, or `name_1.mp3` to `name_3.mp3` for up to three variants chosen at random. A sound that is not in the manifest is never requested, so a missing file causes no error.\n\n';
for (const group of [...new Set(catalog.map((c) => c.group))]) {
  md += `## ${group}\n\n| Sound | Status | Plays in game | When | Length | Search for | ★ |\n|---|---|---|---|---|---|---|\n`;
  for (const c of catalog.filter((x) => x.group === group)) {
    md += `| \`${c.name}\` | ${mark(c)} | ${c.wired ? 'yes' : 'not yet'} | ${c.plays} | ${c.length} | ${c.search} | ${c.priority ? '★' : ''} |\n`;
  }
  md += '\n';
}
const missingPriority = priority.filter((c) => !manifest[c.name]);
md += '## Next to find\n\n';
md += missingPriority.length ? missingPriority.map((c) => `- \`${c.name}\`: ${c.plays} (${c.length})`).join('\n') : 'All priority sounds are present.';
md += '\n';
if (unknown.length) md += `\n## Files not in the catalog\n\n${unknown.map((f) => `- \`${f}\` (rename it, or add it to \`data/sfx-catalog.json\`)`).join('\n')}\n`;
if (extra.length) md += `\n## Ignored: more than ${MAX_VARIANTS} variants\n\n${extra.map((f) => `- \`${f}\``).join('\n')}\n`;
writeFileSync(join(root, 'docs', 'SFX-TRACKER.md'), md);

console.log(`sfx: ${have.length}/${catalog.length} present (${priority.filter((c) => manifest[c.name]).length}/${priority.length} priority). Wrote manifest.json, docs/SFX-TRACKER.md and tools/sfx-data.js`);
if (unknown.length) console.log(`  not in the catalog: ${unknown.join(', ')}`);
if (extra.length) console.log(`  ignored (over ${MAX_VARIANTS} variants): ${extra.join(', ')}`);
